"""added mapping to new feature request

Revision ID: 8e19eeb18f0e
Revises: af51e20298dd
Create Date: 2018-09-02 14:46:45.852616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e19eeb18f0e'
down_revision = 'af51e20298dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_request')
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('client_priority', sa.INTEGER(), nullable=True),
    sa.Column('target_date', sa.VARCHAR(length=25), nullable=False),
    sa.Column('product_area', sa.VARCHAR(length=65), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
