"""Initial migration

Revision ID: 932ef0e31bdd
Revises: 
Create Date: 2018-08-28 14:08:58.873496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932ef0e31bdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientName', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('clientPriority', sa.Integer(), nullable=False),
    sa.Column('targetDate', sa.Date(), nullable=False),
    sa.Column('productArea', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clientPriority')
    )
    op.create_index(op.f('ix_feature_request_title'), 'feature_request', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_request_title'), table_name='feature_request')
    op.drop_table('feature_request')
    op.drop_table('client')
    # ### end Alembic commands ###
